name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install

      - run: npm run build
      - run: npm run doc

      # - name: Create Linux App
      #   working-directory: electron/app
      #   run: npm run dist-linux

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.6
        with:
          package-path: ./website/package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@v1.5.7

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.5.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![Docker Image Version (latest by date)](https://img.shields.io/docker/v/wcjiang/tools)](https://hub.docker.com/r/wcjiang/tools) [![Docker Image Size (latest by date)](https://img.shields.io/docker/image-size/wcjiang/tools)](https://hub.docker.com/r/wcjiang/tools) [![Docker Pulls](https://img.shields.io/docker/pulls/wcjiang/tools)](https://hub.docker.com/r/wcjiang/tools)
            
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/tools/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

            ${{ steps.changelog.outputs.changelog }}

            ```bash
            docker pull wcjiang/tools:${{steps.changelog.outputs.version}}
            ```

            ```bash
            docker run --name tools --rm -d -p 9666:80 wcjiang/tools:${{steps.changelog.outputs.version}}
            # Or
            docker run --name tools -itd -p 9666:80 wcjiang/tools:${{steps.changelog.outputs.version}}
            ```

            Visit the following URL in your browser

            ```bash
            http://localhost:9666/
            ```

      # Create Docker Image
      - name: Create docker-compliant static resources.
        if: steps.create_tag.outputs.successful
        run: npm run docker

      - name: Docker login
        if: steps.create_tag.outputs.successful
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docs image
        if: steps.create_tag.outputs.successful
        run: docker image build -t tools .

      - name: Tags & Push image
        if: steps.create_tag.outputs.successful
        run: |
          echo "outputs.tag - ${{ steps.changelog.outputs.version }}"
          docker tag tools ${{ secrets.DOCKER_USER }}/tools:${{steps.changelog.outputs.version}}
          docker tag tools ${{ secrets.DOCKER_USER }}/tools:latest
          docker push ${{ secrets.DOCKER_USER }}/tools:${{steps.changelog.outputs.version}}
          docker push ${{ secrets.DOCKER_USER }}/tools:latest

      # Create Docker Image in Github
      - name: Login to GitHub registry
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker image
        run: docker build -t ghcr.io/jaywcjlove/tools:main .

      - name: Publish to GitHub registry
        run: docker push ghcr.io/jaywcjlove/tools:main


      - name: Tag docker image (beta) and publish to GitHub registry
        if: steps.create_tag.outputs.successful
        run: |
            echo "version: v${{ steps.changelog.outputs.version }}"
            docker tag ghcr.io/jaywcjlove/tools:main ghcr.io/jaywcjlove/tools:${{steps.changelog.outputs.version}}
            docker push ghcr.io/jaywcjlove/tools:${{steps.changelog.outputs.version}}

  build_windows: 
    needs: [build]
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run hoist

      - run: npm run build
      - run: npm run electron
      - run: npm run build:app

  build_macos:
    needs: [build]
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run hoist
      - run: npm run build
      - run: npm run electron
      - run: npm run build:app

  build_linux:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - run: npm run hoist
      - run: npm run electron
      - run: npm run build:app

  roll_back:
    if: failure()
    needs: [build, build_windows, build_macos, build_linux]
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: '${{ needs.create_tag.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
