name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install

      - run: npm run build
      - run: npm run doc

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.6
        with:
          package-path: ./website/package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@v1.5.3

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.5.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/tools/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

            ${{ steps.changelog.outputs.changelog }}

            ```bash
            docker pull wcjiang/tools:${{steps.changelog.outputs.version}}
            ```

            ```bash
            docker run --name tools6 --rm -d -p 9666:80 wcjiang/tools:${{steps.changelog.outputs.version}}
            # Or
            docker run --name tools6 -itd -p 9666:80 wcjiang/tools:${{steps.changelog.outputs.version}}
            ```

            Visit the following URL in your browser

            ```bash
            http://localhost:9666/
            ```

      # Create Docker Image
      - name: Create docker-compliant static resources.
        if: steps.create_tag.outputs.successful
        run: npm run docker

      - name: Docker login
        if: steps.create_tag.outputs.successful
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docs image
        if: steps.create_tag.outputs.successful
        run: docker image build -f docker/Dockerfile -t tools .

      - name: Tags & Push image
        if: steps.create_tag.outputs.successful
        run: |
          echo "outputs.tag - ${{ steps.changelog.outputs.version }}"
          docker tag tools ${{ secrets.DOCKER_USER }}/tools:${{steps.changelog.outputs.version}}
          docker tag tools ${{ secrets.DOCKER_USER }}/tools:latest
          docker push ${{ secrets.DOCKER_USER }}/tools:${{steps.changelog.outputs.version}}
          docker push ${{ secrets.DOCKER_USER }}/tools:latest